### PR TITLE
Removed createClass as its deprecated

### PR DESCRIPTION
**Pull request by Pintouch**
#10 
- ChangesPlain class syntax
- Change react minimum version in peerDependencies
- Add new prop-types package to dependencies

I changed the minimum version for react as documented on [this commit](https://github.com/reactjs/prop-types/commit/e681b40e07f2c4783265f30b4fcca0f200ad0954)

Let me know if it's good for you.

### CODE REVIEW

**Comment by gre** [comment]
nice!

**Comment by Pintouch** [comment]
I didn't check retro compatibility, maybe it's good to have a new version for react 15.5 and above

**Comment by gre** [comment]
ok let's do that

**Comment by gre** [comment]
thanks for the PR :)

**Pull request merged**
